ICRAR/daliuge

- docker/dfms/Dockerfile_incontext
- docker/dfms/build.sh
I encountered the issue that when checking out a specific version of DaLiuGE (for the sake of reproducibility) and building the corresponding Dockerfile, it would essentially checkout master inside the Docker image.
I have been struggling a bit on the implementation. Reading out the branch/tag from the environment does not work when the build is started from the release tarbal (which has all git info stripped). Also I think the Dockerfile should be portable irrespective of the rest of the repo. 
So in the end I propose to add a Dockerfile for in-context builds and make the build.sh check if setup.py exists, in which case it will copy the context to /daliuge in the container and build. If setup.py does not exist, it will revert to pulling the master and build from there.
> Docker builds of context i.s.o. master

- .travis.yml
- daliuge-common/dlg/common/__init__.py
- daliuge-translator/dlg/dropmake/cwl.py
- daliuge-translator/setup.py
- daliuge-translator/test-requirements.txt
- daliuge-translator/test/dropmake/test_pg_gen.py
This a series of commits that fix the python 2.7 test failures. As mentioned in an earlier email I first took out the test-only dependencies into a new `test-requirements.txt` file, and also included there the necessary bits to ensure the test indirect dependencies are correctly installed.
After fixing the initial dependency conflict problem I found another one, which I also fixed. Once those were fixed yet another problem surfaced, related to how `cwlgen` handles `unicode` objects (it doesn't). I therefore added a fix for that problem as well.
After all these changes the Travis builds are back to green.
> CWL-related fixes for python 2.7 tests

- daliuge-runtime/dlg/manager/node_manager.py
- daliuge-runtime/dlg/rpc.py
- daliuge-runtime/setup.py
This set of changes contains a series of improvements on the inter-node messaging system:
* It creates a single Context object used by both the ZeroMQ publisher/subscriber and the ZeroRPC client/server code of the Node Manager. Previously the ZeroMQ publisher/subscriber, the ZeroRPC server, and each ZeroRPC client created their own Context objects, which implicitly creates a new I/O thread. Reducing these Context objects to a single one reduces this to a single I/O thread shared by all ZeroMQ-based code.
* The naming of most of the internal members of the ZeroMQ publisher/subscriber class has been improved for easier code readibility.
* A docstring has been added to the same class to explain how the code works internally, and which other alternatives have been sought.
* The subscription …
> Messaging consolidation

- daliuge-common/dlg/common/__init__.py
- daliuge-translator/dlg/dropmake/cwl.py
- daliuge-translator/dlg/dropmake/web/lg_web.py
- daliuge-translator/dlg/translator/tool_commands.py
- daliuge-translator/test/dropmake/test_pg_gen.py
Make the "dlg cwl" command output a zip file to stdout when no output file is specified by the user.
The main change is in tool_commands.py, where the cwl command now uses _open_o() with opts.output to send output to stdout.
Other changes are:
- modified input parameters to create_workflow() and create_command_line_tool(). Previously, these methods wrote the intermediate workflow and step files to disk, before combining the files into a zip file for output. Now the contents of the workflow and steps are held in strings, used to create io.BytesIO objects, and the zip file is built in memory.
- added a common.s2b() method, since the io.BytesIO() method requires "byte-like" input in Python 3. I'd be interested in feedback on this approach.
> YAN-424 - CWL output to stdout

- Dockerfile.ray
- daliuge-engine/dlg/apps/archiving.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/droputils.py
- daliuge-engine/dlg/io.py
- daliuge-engine/dlg/manager/cmdline.py
- daliuge-engine/dlg/ngaslite.py
- daliuge-engine/dlg/utils.py
- daliuge-engine/docker/Dockerfile
- daliuge-engine/run_engine.sh
- daliuge-engine/show_DIMlogs.sh
- daliuge-engine/show_NMlogs.sh
- daliuge-engine/start_local_managers.sh
- daliuge-engine/stop_engine.sh
- daliuge-engine/test/apps/test_simple.py
- daliuge-translator/test/dropmake/logical_graphs/Plasma-test.graph
- scripts/start_dim.sh
- scripts/start_nm.sh
- scripts/stop_dim.sh
- scripts/stop_nm_daemon.sh
Mostly fixes to NgasLiteIO, but also some other small changes.
> Ngas lite mods

- daliuge-engine/dlg/manager/web/static/js/dm.js
The client-side javascript repeatedly calls the updateGraph function to fetch the status of all nodes in graph. Upon receiving a reply, updateGraph determines whether all the nodes are complete using a reduce() function and stores the result in a variable called 'allCompleted'.
Once the value of allCompleted becomes true, the status of the whole session is queried and the result, which should be 'finished' is added to the HTML to be visible to the user.
Previously, the reduce function would only consider nodes as complete if their status was 'completed', 'error' or 'cancelled'. However, since some nodes only achieve the 'finished' state, allCompleted would never become true, and therefore the session state would not progress past 'running' (until the page was reloaded, or a different …
> Correctly update the "status" text on the DIM session view 

- daliuge-engine/dlg/apps/dockerapp.py
- daliuge-engine/test/apps/test_docker.py
Docker containers run by default under /. Additionally, when we ensure
and create a new user in the container, we run under /home/r ("r" is the
new user). Both of these options make it impossible to retrieve anything
from the working directory after execution finishes though, which is why
we need a new parameter that lets users specify under which directory
the container command will run (and thus they can also map it from the
host system).
This commit adds support for a new workingDir parameter in DockerApps.
Its value defaults to "/", and is only taken into account when the image
from which the container is started doesn't already contain a value for
its WorkingDir specification. We take care that this preference is
obeyed both when we internally create a new user, as well as when we …
> Add workingDir parameter to DockerApp

- daliuge-engine/dlg/manager/cmdline.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/dlg/manager/session.py
- daliuge-engine/test/manager/test_dim.py
- daliuge-engine/test/test_session.py
Generate individual log files per session and propagates default/user specified log file location.
> LIU-65: Generate individual log files per session.

- daliuge-engine/dlg/manager/web/dm.html
Calculating dimIP should only happen when needed, but more importantly
only when possible. Doing it outside the `if` statement crashes the
script that runs when the node manager UI (which doesn't have a dim_url
parameter) loads, crippling its functionality.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
> Reference dimUrl only when available

- daliuge-engine/dlg/apps/simple.py
- daliuge-engine/dlg/ddap_protocol.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/manager/web/session.html
- daliuge-engine/dlg/manager/web/static/css/session.css
- daliuge-engine/dlg/manager/web/static/js/dm.js
- daliuge-engine/test/test_drop.py
Branch drops are a special type of application drops that must implement
an additional condition function, returning true or false, and thus
triggering one branch of execution down the rest of the graph, or the
other. The current implementation requires these applications
to have exactly two outputs, mainly because the information of which
branch should continue executing is transmitted through the output drop
onto its corresponding consumers instead of trying to contact the
consumers directly.
To support this new functionality we require a new SKIPPED state, which
automatically propagates through the graph. Unit tests check that this
propagation works through multiple levels, both for data and application
drops, such that their respective states change correctly (which is
important for …
> LIU-96 Add initial support for Branch drops

- OpenAPI/translator.yaml
- daliuge-translator/dlg/dropmake/web/lg_web.py
Updated the method to look for a 'test' parameter.
If found, it uses the existing functionality in unroll() to replace all apps with dlg.apps.simple.SleepApp. If not found, we pass app=None to unroll(), which leaves the original apps unchanged.
> Updated unroll_and_partition_with_params() to look for an incoming 'test' parameter

- daliuge-engine/dlg/apps/dockerapp.py
- daliuge-engine/setup.py
- daliuge-translator/dlg/dropmake/pg_generator.py
- docs/conf.py
The `removeContainer` option currently does not remove stopped docker containers. Docker already provides a technique for automatically removing containers once stopped so I've updated the engine discarding logic to use the builtin docker autoremove. The other issue is that some containers never finish execution `container.stop` needs to be called seperately to `container.wait`. I've updated such that if this happens when the drop state changes away from running, however `stop()` can sometimes be a slow operation. On this side of this I've found an issue with a invalid unexpected boolean strings formats being sent to the translator.
Testing with the plasma dockerapp containers are now always cleaned up by default as long as the graph is cancelled at the end to stop the plasma stores.
> LIU-165 Automatically remove dockerapp containers

- daliuge-engine/dlg/io.py
Numerous python libraries accept the buffer protocol for reading in-memory data (in some cases with zero copy). This change add the buffer() getter that gets used by nifty gridder for reading .npy format data. e.g.
```python
def drop_to_numpy(drop) -> np.ndarray:
bio = drop.getIO()
bio.open(OpenMode.OPEN_READ)
buf = bio.buffer()
res = np.load(io.BytesIO(buf))
bio.close()
return res
def numpy_to_drop(array: np.ndarray, drop):
buf = io.BytesIO()
np.save(buf, array)
drop.write(buf.getbuffer())
```
> LIU-207 expose buffer protocol getter for data drops

- daliuge-translator/dlg/dropmake/dm_utils.py
- daliuge-translator/dlg/dropmake/pg_generator.py
- daliuge-translator/dlg/dropmake/scheduler.py
- daliuge-translator/dlg/dropmake/utils/antichains.py
- daliuge-translator/setup.py
As per https://networkx.org/documentation/latest/release/release_2.4.html,
NetworkX uses `Graph.nodes[u]` to access a node `u` in the Graph.
This update changes any `DiGraph.node[u]` access to `DiGraph.nodes[u]`.
> REF: https://github.com/ICRAR/daliuge/issues/83

- daliuge-engine/dlg/droputils.py
- daliuge-engine/dlg/io.py
- daliuge-translator/dlg/dropmake/pg_generator.py
I've noticed that the translator is currently trying to create a service drop and the input app into the physical graph which is causing _create_test_drop_spec to raise an exception (I get the impression that this method wasn't intended for production)
I've updated the logic in lgn_to_pgn to explicitly filter out the parent node from the graph and change the child to service_app type in `make_single_drop`.
pg_generator.py is getting quite is large so I propose a refactor with pg.py, pgt.py and pgtp.py seperated out
> LIU-165: Service Drops Fix

- daliuge-common/dlg/common/__init__.py
- daliuge-engine/dlg/apps/scp.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/graph_loader.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/test/manager/test_dm.py
- daliuge-engine/test/test_drop.py
- daliuge-engine/test/test_graph_loader.py
- daliuge-translator/test/dropmake/logical_graphs/SharedMemoryTest.graph
- daliuge-translator/test/dropmake/test_pg_gen.py
- docs/architecture/graphs.rst
This merge transforms the underlying SharedMemory implementation used to facilitate multiprocessing (YAN-847) into stand-alone drops for explicit use.
Some documentation has been added to the ``graphs`` page in the docs.
Unlike the multiprocessing implementation, there is no fall-back to standard InMemory drops in the case of an incompatible system (Windows or python < 3.8) - it is assumed that specifically requesting shared memory is intentional.
> Yan 854 -- Shared Memory DROPs

- daliuge-engine/dlg/apps/dockerapp.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/io.py
- daliuge-engine/test/test_drop.py
- daliuge-translator/dlg/dropmake/pg_generator.py
In https://icrar.atlassian.net/browse/LIU-213 I noticed issues when writing large amounts of data to plasma stores. The primary issue was not allocating enough shared memory to plasma store container.
There is also a performance issue with plasmaIO is how previously bufferOutputStream uses a resizeable staging buffer before copying to plasma memory. Instead it is possible to create a fixed size plasma buffer and copy directly into it to improve drop performance in cases where drop size is known or only a single write is performed at runtime. To continue support of the old behaviour I've added a "use_staging" drop argument which indicates data will be copied to a resizeable buffer first before copying to plasma memory.
> LIU-213 docker and plasma shared memory improvements

- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/s3_drop.py
Data drop palettes currently exist in EAGLE template.palette but could be generated from the respective components in Daliuge using the palette generator. Here I've converted the drop definitions to doxygen where the the source is located.
> LIU-213 add data drop doxygen definitions

- daliuge-common/dlg/common/__init__.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/environmentvar_drop.py
- daliuge-engine/dlg/graph_loader.py
- daliuge-engine/dlg/parset_drop.py
- daliuge-engine/dlg/utils.py
- daliuge-engine/test/test_ParameterSetDROP.py
- daliuge-engine/test/test_environmentvars.py
- docs/architecture/graphs.rst
Adds a new EnvironmentVariableDROP which acts as a KeyValue store. Incidentally adds a KeyValueDROP abstract type which can be mixed in with other drops if needed. These variables can be referenced as parameters in EAGLE, DALiuGE handles translating and fetching these references at runtime.
Limitations:
- Values are static. The interface has room for a GET(key) operation, but owing to potential difficulties with shared memory I suggest this is better dealt with by another service, such as Redis, for example.
- Environment variables are not automatically pulled in at runtime. Drops need to call 'auto_fill_environment_vars()' to trigger the parsing of these variable references. This decision reflects the possibility to add producers/inputs after the initialization of the drop object itself. …
> Liu 220 - Environment Variable Drop 

- .travis.yml
- daliuge-engine/dlg/apps/archiving.py
- daliuge-engine/dlg/apps/bash_shell_app.py
- daliuge-engine/dlg/apps/crc.py
- daliuge-engine/dlg/apps/dockerapp.py
- daliuge-engine/dlg/apps/dynlib.py
- daliuge-engine/dlg/apps/mpi.py
- daliuge-engine/dlg/apps/plasma.py
- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/apps/scp.py
- daliuge-engine/dlg/apps/simple.py
- daliuge-engine/dlg/apps/socket_listener.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/s3_drop.py
- tools/xml2palette/xml2palette.py
Changes to the xml2palette script to allow users to build a palette from a subset of component descriptions within the input code that match a given tag.
For DALiuGE we generate two palettes:
- one containing the components with the "template" tag, resulting in the "Raw Components" palette for EAGLE
- one containing the components with the "daliuge" tag, resulting in the "DALiuGE Components" palette for EAGLE
I've added Doxygen comments to a number of classes, in order the generate additional components. I changes some @par doxygen commands to @param, since the former is not picked up by xml2palette.py.
I've updated the section of xml2palette that automatically adds some of the "component" parameters, such as "Execution time", to components with specific categories. I think this should be …
> Liu 221 - Generate template.palette in DALiuGE

- daliuge-engine/dlg/apps/simple.py
Partitioned nifty gridding I've tested works perfectly when adding frequency split dirty images that have not been normalized.
For gathering I've made a gather app this time can perform a variety of different types of reductions with memory efficiency in mind such that only two input drops need to be loaded in memory during execution. I've only included simple commutative reduce functions (no mean, median) to ensure reduction is correct even when staged in a tree.
It may be possible to perform parallel reduce in one node using `import multiprocessing`, ideally though this would be done with a special TreeReduce node instead of Gather to work across multiple compute nodes
> GenericNpyGatherApp

- daliuge-common/build_common.sh
- daliuge-common/docker/Dockerfile.cuda
- daliuge-engine/build_engine.sh
- daliuge-engine/dlg/apps/simple.py
- daliuge-engine/docker/Dockerfile.devall
- daliuge-engine/run_engine.sh
Added 2 extra buildscript targets I regularly use for nifty component development.
`build_common.sh devcuda` includes the setup of cuda enabled docker images (cuda development files and not nvidia drivers).
`build_engine.sh devall` includes extra python components that may require extra apt packages and use different licenses.
> Extra docker build targets

- daliuge-engine/dlg/apps/archiving.py
- daliuge-engine/dlg/apps/bash_shell_app.py
- daliuge-engine/dlg/apps/crc.py
- daliuge-engine/dlg/apps/dockerapp.py
- daliuge-engine/dlg/apps/dynlib.py
- daliuge-engine/dlg/apps/mpi.py
- daliuge-engine/dlg/apps/plasma.py
- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/apps/scp.py
- daliuge-engine/dlg/apps/simple.py
- daliuge-engine/dlg/apps/socket_listener.py
- daliuge-engine/dlg/drop.py
Just added three new cparams to the Doxygen comments.
The build fails, but this change is just comments and whitespace, so I think it is OK.
The number of cparams is getting quite large for some of these components, quite a lot of comment boilerplate. We should probably investigate a better way to do this at some stage.
> Doxygen updates to include input_error_threshold, n_effective_inputs, n_tries component parameters in appropriate components

- daliuge-engine/dlg/drop.py
Somehow, there ended up being three copies of ParameterSetDrop across two files
I have removed two of them in drop.py leaving the only implementation in parset_drop.py
> Removes spurious duplicates of Parset_drop implementations.

- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/environmentvar_drop.py
- daliuge-engine/dlg/graph_loader.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/dlg/manager/session.py
- daliuge-engine/dlg/utils.py
- daliuge-engine/test/test_environmentvars.py
- daliuge-translator/dlg/dropmake/pg_generator.py
A slight pivot away from embedding a single variable store in all graphs.
We now rely on fetching DLG_ prefixed parameters from the deployment environment itself.
Responsibility propagating such variables throughout a deployment has shifted to deployment scripts and configs rather than cluttering the graphs.
More specialised 'global variables' can be handled by manually adding an environment variable store to the graph.
Additionally, DROPs are now forced to fetch their environment variables at init time, which requires some careful dictionary management.
> Yan 891 - Support for default ENV variable store 

- daliuge-common/build_common.sh
- daliuge-common/docker/Dockerfile.devcuda
- daliuge-engine/dlg/apps/simple.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/docker/Dockerfile.devall
- daliuge-engine/run_engine.sh
- daliuge-translator/build_translator.sh
- daliuge-translator/docker/Dockerfile.dev
Done a fresh test with nifty gridding graphs and made a few necessary deployment changes and a bugfix on the gather component. As far as I can tell there is still not full support application paramaters, only component parameters so I've updated the daliuge derived palettes to use cparams
> YAN-973 Nifty gridder testing

- daliuge-translator/dlg/dropmake/web/graph_init.js
- daliuge-translator/dlg/dropmake/web/lg_web.py
- daliuge-translator/dlg/dropmake/web/main.js
- daliuge-translator/dlg/dropmake/web/pg_viewer.html
Previously, if input JSON to the translator failed validation against the schema, no translation would take place, and the validation error is all that would be shown.
Now, the validation error, if one occurs, will be recorded and sent to the client along with the translated graph. The client will display the validation error to the user.
Updated translator to use a modal dialog for errors, instead of the native javascript alert().
One side effect: Previously, REST and HELM deploy failures would produce many (blocking) javascript alert()s in a row. Now, the first error in the deploy is not blocking, and the deploy continues, potentially overwriting the contents of the error dialog with subsequent errors. So when the REST and HELM deploy functions generate many errors, only the last error …
> Yan 945 - Improved display of LG schema errors 

- daliuge-engine/dlg/manager/composite_manager.py
- daliuge-engine/test/manager/test_dim.py
- daliuge-translator/dlg/dropmake/web/lg_web.py
PR #133 added a signature mechanism, which passes additional information alongside a graph from translation to execution.
The default value of this 'reprodata' in the PGT object is an empty dictionary but will non-empty if prior layers called their respective init_lgt/lg_reprodata functions. 
Since EAGLE is not yet configured to pass a reproducibility mode flag to the translator (yet), these functions are never called, leaving the PGT with the default value of an empty dictionary.
There is logic in the composite_manager when loading a graph to remove the appended reprodata, avoiding loading this information as a drop by checking if the last item in the dropspec (which is expected to be the reprodata) contains an rmode flag. This failed if the final drop in the list is an empty dictionary, …
> Liu 253 - Issue with appended reprodata

- daliuge-engine/setup.py
pyzmq which is a dependency of zerorpc just released version 23.0.0 but contains breaking changes when running `dlg daemon -vv` with the following exception:
```
Traceback (most recent call last):
File "/dlg/bin/dlg", line 8, in <module>
sys.exit(run())
File "/dlg/lib/python3.8/site-packages/dlg/common/tool.py", line 166, in run
commands[cmd][1](sys.argv[1:])
File "/dlg/lib/python3.8/site-packages/dlg/common/tool.py", line 106, in wrapped
f(parser, *args, **kwargs)
File "/dlg/lib/python3.8/site-packages/dlg/common/tool.py", line 100, in __call__
return getattr(module, fname)(*args, **kwargs)
File "/dlg/lib/python3.8/site-packages/dlg/manager/proc_daemon.py", line 392, in run_with_cmdline
daemon = DlgDaemon(opts.master, opts.noNM, opts.noZC, opts.verbose - opts.quiet)
File …
```
> pyzmq version lock

- daliuge-engine/docker/Dockerfile.devall
- daliuge-engine/run_engine.sh
Minor daliuge-engine docker dependency changes for better cuda compatibility, rebase of https://github.com/ICRAR/daliuge/pull/137
> YAN-973 test nifty cuda docker image

- daliuge-common/docker/Dockerfile.devcuda
- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/meta.py
- daliuge-engine/docker/Dockerfile.devall
- daliuge-engine/test/apps/test_pyfunc.py
- daliuge-engine/test/apps/test_simple.py
- daliuge-engine/test/graphs/funcTestPG_namedPorts.graph
- daliuge-engine/test/graphs/pyfunc_glob_testPG.graph
Previously pyfunc apps parsed both input and output drop contents using pickle or ast based on the pickle parameter. This however lead to the problem that a graph using only pyfunc apps either uses pickle everywhere or ast everywhere, so this change firstly split this param for all inputs and all outputs. Additionally I've changed the param to an enum type, namely one of pickle, ast, and path, however others can be added. Path is useful for functions that manually read from a file format by filename whilst at the same time using a filedrop.
rebase of https://github.com/ICRAR/daliuge/pull/154
e.g.
> LIU-251 Add Pyfunc Port Parser Options

- docs/architecture/reproducibility/blockdags.rst
- docs/architecture/reproducibility/rmodes.rst
Remarks on where reprodata is stored throughout the translation and after execution.
> Updates blockdags.rst with storage note

- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/droputils.py
- daliuge-engine/test/apps/test_pyfunc.py
- daliuge-engine/test/test_droputils.py
- docs/development/app_development/app_index.rst
- docs/development/app_development/datadrop_io.rst
- docs/development/app_development/pyfunc_components.rst
- docs/development/app_development/python_components.rst
- docs/development/app_development/special_components.rst
Added documentation and tests for several changes made to python components and pyfunc components in YAN-969. After changes in https://github.com/ICRAR/daliuge/pull/159 it's also no longer required to cast enum params in the run method.
> YAN-969 docs and tests

- daliuge-common/dlg/clients.py
- daliuge-engine/dlg/manager/composite_manager.py
- daliuge-engine/dlg/manager/proc_daemon.py
- daliuge-engine/dlg/manager/rest.py
- daliuge-engine/dlg/nm_dim_assigner.py
- daliuge-engine/test/manager/test_daemon.py
- Adds REST APIs for MM to add/remove DIMs & Nodes from DIMs
- Adds zeroconf discovery of DIMs
- Adds nm_dim_assigner - assigns NMs to DIMs as they come on/off-line
- Adds associated tests asserting this functionality works when zeroconf is enabled, and does not work when disabled.
Limitations: 
- Does not handle multiple DIMs
- Performs no assignments with more than a single DIM
> Liu 186 - Register DIM with zeroconf with MM 

- daliuge-engine/test/manager/test_daemon.py
These changes are to speed up the daemon tests, and simplify the test code as I mentioned I'd try to do in https://github.com/ICRAR/daliuge/pull/156#pullrequestreview-987020751. See individual commit messages for more details.
In particular I'd like to make sure the tests are testing the right thing with the last commit. As I mention in my message, coverage stays the same and the tests all still pass, so while I'm 50% sure I did the right thing, I'd still like a second pair of eyes to corroborate it.
> Liu 186 post changes

- daliuge-common/dlg/common/__init__.py
- daliuge-engine/dlg/deploy/common.py
The removal of the last node in the PG seems to correspond to the logic
of that last node having the reproducibility data of the graph instead
of an actual drop specification (this is the implication I gathered by
looking at the rest of the changes in 58138a30b, the commit where this
change was introduced). This reproducibility data is optional though,
and therefore the "dlg submit" tool, via this submit() function, was
broken and removed the last drop specification from the calculation of
the graph roots, which in turn had the effect that the session didn't
trigger one of the roots of the graph at graph submission time, leaving
the graph in Running state forever.
This change fixes the submission of "normal" graphs (i.e., without the
extra reproducibility data object at the end), making …
> Correctly calculate roots of PG before submission

- daliuge-engine/dlg/rpc.py
One of the problems with the current multiprocessing support in daliuge
is that it requires too many resources. This is because each DropProxy
object is creating its own RPCClient, which internally create their own
ZMQ context. This not only increases the runtime requirements of the
system (more objects need to be created, etc.) but also puts pressure on
system resources. This situation is described in detail in YAN-976, and the
test/manager/test_dm.py::TestDM::test_many_relationships unit test in
particular triggers this issue with ease.
This commit implements a partial fix for this issue. While it doesn't
take care of the problem itself, it identifies when a DropProxy is
created from a NodeManager that is *not* using multiprocessing support,
and avoid creating an RPCClient instance …
> Lessen resource usage when multiprocessing not in use

- daliuge-engine/test/manager/test_dm.py
These tests are not stable (see YAN-976 for some examples), but their
instability has been hidden by the fact that they are never run on
Travis anyway. On my laptop though they often cause issues, making the
whole test suite unreliable.
This commit changes the skip condition for the multiprocessing tests to
only run if a specific environment variable is set (it isn't by
default). This will allow us to continue hiding the problem, but in a
more controller manner, while also giving us an easy switch to turn the
tests on when we start addressing their problems.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
> Skip multiprocessing tests by default

- .pylintrc
- .travis.yml
- daliuge-engine/dlg/apps/bash_shell_app.py
- daliuge-engine/dlg/apps/dynlib.py
- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/dask_emulation.py
- daliuge-engine/dlg/deploy/dlg_proxy.py
- daliuge-engine/dlg/deploy/utils/monitor_replayer.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/io.py
- daliuge-engine/dlg/lifecycle/hsm/manager.py
- daliuge-engine/dlg/lifecycle/hsm/store.py
- daliuge-engine/dlg/lifecycle/registry.py
- daliuge-engine/dlg/manager/cmdline.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/dlg/ngaslite.py
- daliuge-engine/dlg/restserver.py
- daliuge-engine/test/integrate/chiles/chilesdo.py
- daliuge-engine/test/manager/test_scalability.py
- daliuge-translator/dlg/dropmake/lg.py
- daliuge-translator/dlg/dropmake/pgt.py
- daliuge-translator/dlg/dropmake/pgtp.py
- daliuge-translator/dlg/dropmake/web/lg_web.py
These changes unify the logging statements in daliuge to use lazy, %-based formatting. This is later enforced by adding the relevant pylint rules (the first ones ever, so everything is switched off except the new rules), and then adding a CI job that run pylint to check new commits don't offend the rules.
This implements https://jira.skatelescope.org/browse/YAN-981.
> Improve daliuge logging

- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/graph_loader.py
These changes speed up the daliuge-engine runtime when submitting big graphs, which is done by our `test_scalability` test. I noticed the test was taking longer than it used to: about 50, 60 seconds now when it previously finished in less than 10. After some profiling I found two bottlenecks:
* The `removeUnmetDependencies` function during graph addition (before actual deployment) due to unnecessary object creation in tight loops.
* The `drop._extract_members` function, which wasn't using caching between different drop instantiations.
With these changes the `test_scalability` walltime comes down by ~40 seconds; after these are applied most of the time is spent building reproducibility data on the graph, but that can be tackled separately.
> Speedup instantiation of bigger graphs

- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/lifecycle/dlm.py
- daliuge-engine/dlg/manager/cmdline.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/dlg/rpc.py
- daliuge-engine/dlg/testutils.py
- daliuge-engine/test/lifecycle/test_dlm.py
- daliuge-engine/test/manager/test_dm.py
This set of commits implement a change in how the DLM can be configured. While previously it could be either fully enabled or fully disabled, it now can be started in such a way that users can select which of its features should be on or off. These features are:
* Automatic data replication
* Automatic data expiration
* Automatic data deletion (needs the former to work)
These changes are reflected not only in the DLM API, but also on the usage of new command-line switches for the `dlg nm` command. The old `--no-dlm` switch is still present but deprecated, and translates to disabling all features on the DLM.
Now that more fine-grained behavior can be used, the default is to *enable* data expiration and deletion, but keep data replication disabled. This is in the spirit of keeping system …
> DLM revisit: fine-grained control on which tasks can run

- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/environmentvar_drop.py
- daliuge-engine/dlg/s3_drop.py
Added default input and output ports to all data component doxygen documentation, except for EnvironmentVariables and ParameterSet, which do not have input ports.
All ports were named 'dummy' and are of type 'Complex'
> Liu 262 data component default ports

- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/apps/simple.py
- daliuge-engine/dlg/lifecycle/dlm.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/test/apps/test_simple.py
These commits remove memory leaks present in some daliuge built-in applications. In particular the RandomArray and PyFunc apps held some data in the drop instance. In the case of the former this was used for unit testing, so I've left the behavior in, but under a new component parameter (defaulting to *not* keep the data around). In the latter case holding onto the data was unnecessary.
We also evidenced an effect where deleting a session wouldn't release all the memory associated to all its drops, even though drops should be all destroyed by that time. This turned out to be a side-effect of turning on the DLM: even after a session was deleted, its drops would still be tracked by the DLM. I have therefore added the necessary code to untrack drops from sessions that are about to be …
> YAN-1048 Remove memory leaks

- daliuge-engine/dlg/manager/web/static/js/dm.js
reduce function now accepts 'expired', 'deleted' drops contributing to a 'finished' status - which is in fact the case but was not showing as such before.
> Session status view now updates with session status correctly.

- daliuge-engine/dlg/drop.py
Changed to use the checksum provided by NGAS if available (extremely likely), else use ID data, rather than hashing the entire contents.
> Changes NGAS reproduce data 

- daliuge-engine/dlg/manager/cmdline.py
- daliuge-engine/dlg/manager/web/static/css/progressBar.css
This MR changes the colours of expired and deleted drops to a dark grey and black with white font respectively.
Additionally, this PR reduces the default garbage collection period to 30 seconds (down from 100).
Attached is an imaging showing deleted, expired and cancelled drops for reference.
> Liu 277 - Changing colour of expired and deleted drops 

- daliuge-translator/dlg/dropmake/pg_generator.py
- daliuge-translator/dlg/dropmake/pgt.py
- daliuge-translator/dlg/dropmake/pgtp.py
- daliuge-translator/dlg/dropmake/scheduler.py
- daliuge-translator/dlg/dropmake/utils/antichains.py
- daliuge-translator/dlg/dropmake/web/lg_web.py
- daliuge-translator/test/dropmake/test_lgweb.py
The PR mostly corrects the behaviours of several translation algorithms.
By adding tests for each translation algorithm specifically, their validity is confirmed (although there are still some ways to go for correctness testing). The PSO option in particular used outdated networkX calls and handled DOP incorrectly.
In future, re-implementing the entire translator should be considered.
> Liu 303 - Correcting Scheduler Algorithms

- .github/workflows/create-palettes.yml
- tools/xml2palette/xml2palette.py
Add data_hash and signature data generated by BlockDAG module into palettes JSON. I use build_block_dag() to generate data for the palette that is being built. It largely follows the example use of build_block_dag() from within the BlockDAG code.
From the BlockDAG data:
- the "data_hash" attributes are copied to each component in the palette (as the attribute "dataHash")
- the "signature" attribute for the whole set of components is copied into the palette (as the attribute "signature")
The additional information will be used in EAGLE to update components within existing graphs.
I'll create a PR for the associated EAGLE work soon.
> Yan 1070 - add data_hash and signature attributes from BlockDAG to EAGLE palette JSON

- daliuge-common/dlg/common/reproducibility/reproducibility.py
- daliuge-engine/test/deploy/test_common.py
- daliuge-engine/test/manager/test_dim.py
- daliuge-engine/test/manager/test_dm.py
- daliuge-engine/test/manager/test_mm.py
- daliuge-engine/test/manager/test_rest.py
- daliuge-engine/test/manager/test_scalability.py
- daliuge-engine/test/reproducibility/test_lg_blockdag.py
- daliuge-engine/test/reproducibility/test_pg_blockdag.py
- daliuge-engine/test/reproducibility/test_toposort.py
- daliuge-engine/test/test_session.py
- daliuge-translator/test/reproducibility/test_accumulatedata.py
- daliuge-translator/test/reproducibility/test_integration.py
- daliuge-translator/test/reproducibility/test_repro_inits.py
- daliuge-translator/test/reproducibility/test_scatter_blockdag.py
Originally, it was assumed that there would only be one rmode per graph, so the json was structured as {reprodata: {hash: x}} etc.
Allowing an 'ALL' mode added an extra layer to this - {reprodata: {RERUN: {hash: x}, REPEAT: {hash: x}}} etc.
This split the implementation into two branches - messy and difficult to follow.
This PR unifies the structure into {reprodata: {RMODE: {hash:x}}} even for a single rmode.
> Refactors reprodata to make storage consistent

- daliuge-engine/setup.py
- daliuge-engine/test/manager/test_daemon.py
Upon a recent MR, the test_daemon.py started failing. 
This is related to zeroconf 0.39.2 - for now, I'm pinning the version at ~=0.38.4 as a workaround, but we should try to support upgraded versions.
Additionally, this MR adds Boto3 as a dependency, since errors trying to find it were polluting the log files.
> Patch daemon tests

- daliuge-engine/setup.py
Following the [deprecation of pyarrow](https://arrow.apache.org/docs/python/plasma.html), to avoid further build errors, we pin pyarrow to 9.0.0
> Pins pyarrow to 9.0.0 to sidestep deprecation.

- daliuge-engine/dlg/data/drops/parset_drop.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/event.py
- daliuge-engine/test/test_event.py
- daliuge-engine/test/test_input_fired_app_drop.py
Alright, attempt no. 2: now with correct ticket numbers. This supersedes #214.
I've retained the type-hints and one of the tests I originally added in #214 as there were no functional changes there and there's no point throwing away those enhancements (plus it was useful for adding further tests below).
Exception handling is now encapsulated around the invocation of `execute()` in `async_execute()` with a helper method which wraps the call in `try/except`. 
I didn't realise this until I went to write the tests, but this logic only occurs in a `InputFiredAppDROP` which means I've only fixed this case for drops of that type. I expected this logic to be on `AbstractDrop` which is why I suspect I may have originally led myself to do this handling in the `EventFirer`. Though now I think about …
> LIU-322: Catch async exceptions

- daliuge-common/dlg/common/reproducibility/reproducibility.py
When executing with the NOTHING rmode, there is no reprodata to append or process. At higher levels (pgt, pg, etc.) building the blockdag is skipped when executing with the NOTHING rmode, and the same should happen at the runtime level. This MR covers the missing case.
> Catches unhandled NOTHING case in building reprodata

- daliuge-engine/dlg/apps/app_base.py
- daliuge-engine/dlg/apps/bash_shell_app.py
- daliuge-engine/dlg/apps/dockerapp.py
- daliuge-engine/dlg/apps/dynlib.py
- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/data/drops/data_base.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/graph_loader.py
- daliuge-engine/dlg/manager/cmdline.py
- daliuge-engine/dlg/manager/composite_manager.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/dlg/manager/session.py
- daliuge-engine/dlg/rpc.py
- daliuge-engine/dlg/runtime/__init__.py
- daliuge-engine/lib64_dist.pth
- daliuge-engine/test/apps/test_bash.py
- daliuge-engine/test/apps/test_docker.py
- daliuge-engine/test/apps/test_dynlib.py
- daliuge-engine/test/apps/test_dynlib2.py
- daliuge-engine/test/apps/test_pyfunc.py
- daliuge-engine/test/apps/test_simple.py
- daliuge-engine/test/manager/test_dm.py
- daliuge-engine/test/test_input_fired_app_drop.py
- daliuge-translator/dlg/dropmake/web/translator_rest.py
- daliuge-translator/test/dropmake/logical_graphs/nagsIo.graph
This builds off work that @rtobar started on in [multiproc-drop-apps](https://github.com/ICRAR/daliuge/compare/master...multiproc-drop-apps2), with some slight renaming and simplifying to use `ProcessPoolExecutor` instead of manually managing a pool of processes. I've also fixed some unrelated tests that started failing: NGAS (updated domain, and skipped tests) and `lgweb` (a newer version of Pydantic seems to be stricter). 
If no node manager is present, drops will run synchronously, otherwise they will use the provided `DropRunner`, which will either do work in threads or processes. To avoid complicated state synchronisation across processes, it's actually the drop's `run()` method that gets run in the `DropRunner`, not the whole `execute()` method. 
Unfortunately this complicates the …
> Drop MultiProcessing

- daliuge-common/setup.py
The version of `merklelib` [currently stored on Pypi](https://pypi.org/project/merklelib) is not up-to-date with the repository, which means we do not have changes that make it compatible with Python 3.10 (https://github.com/vpaliy/merklelib/pull/10). 
We could point to the GitHub repository instead of trying for the Pypi project, but unfortunately there are outstanding issues with the setup.py that have not been remedied (https://github.com/vpaliy/merklelib/pull/11). 
@pritchardn has a repository that is up-to-date with the original/base repository, and we have merged a fix for the setup.py script (see https://github.com/pritchardn/merklelib/pull/1). 
We will use this version of the merkelib moving forward and pull it directly from GitHub when installing DALiuGE. 
Confirmed the …
> Update merklelib to support Python3.10

- daliuge-common/dlg/utils.py
- daliuge-common/docker/Dockerfile
- daliuge-common/docker/Dockerfile.casa
- daliuge-common/docker/Dockerfile.devcuda
- daliuge-common/docker/Dockerfile.ray
- daliuge-engine/build_engine.sh
- daliuge-engine/dlg/graph_loader.py
- daliuge-engine/dlg/manager/composite_manager.py
- daliuge-engine/dlg/manager/node_manager.py
- daliuge-engine/dlg/manager/rest.py
- daliuge-engine/dlg/manager/session.py
- daliuge-engine/dlg/rpc.py
- daliuge-engine/docker/Dockerfile
- daliuge-engine/docker/Dockerfile.casa
- daliuge-engine/docker/Dockerfile.dev
- daliuge-engine/docker/Dockerfile.devall
- daliuge-engine/docker/Dockerfile.ray
- daliuge-engine/docker/Dockerfile_incontext
- daliuge-engine/run_engine.sh
- daliuge-translator/build_translator.sh
- daliuge-translator/dlg/dropmake/pgt.py
- daliuge-translator/dlg/dropmake/web/translator_rest.py
- daliuge-translator/docker/Dockerfile
- daliuge-translator/docker/Dockerfile.ray
- daliuge-translator/run_translator.sh
- daliuge-translator/test/dropmake/test_pg_gen.py
This pull requests adds avahi ( mDNS/DNS-SD) to all docker targets. This allows the images to announce themselves as dlg-trans.local and dlg-engine.local, respectively and makes managing the internal connections easier. These names have also been added to the CORS configurations, including OOD.
> Added avahi to all targets

- daliuge-engine/dlg/named_port_utils.py
_Note: These changes were originally raised in #245._
**Bug**
The positional parameter option currently does not work for Docker and Bash applications. For example, the **wsclean_data_local.graph** has the Docker-contained `wsclean` with the following input parameter that is marked as a positional parameter: 
However, the graph fails on deployment because the `msname` property is incorrectly processed as a keyword argument, even thought it is set as **"positional"** in the UI above. This leads to the `-msname` property being passed to `wsclean` as opposed to just the file name: 
```
/bin/bash -c "wsclean -size 512 512 -scale 0.7amin -pol I -spws 0 -niter 10000 -auto-threshold 3 -padding 1 -msname /home/rwb/dlg/workspace/wsclean_data_local12_2024-04-26T12-00-40.261395/MWA-single-timeslot.ms …
```
>  Bug fix - Temporary solution to address positional arguments not working #245 

- daliuge-engine/dlg/data/drops/data_base.py
- daliuge-engine/dlg/data/drops/file.py
- daliuge-engine/dlg/data/drops/memory.py
- daliuge-engine/dlg/drop.py
- daliuge-engine/dlg/lifecycle/dlm.py
- daliuge-engine/test/lifecycle/test_dlm.py
**Problem**
This PR partially addresses LIU-368, which aims to enable proper persistence of data drops. 
Currently, the `persist` and `expireAfterUse` flag are coupled together. This is orthogonal to the original behaviour, in which the expiry of the drop data should have no bearing on the persistence of the data (which would ensure it is copied elsewhere). 
This PR partially addresses this work by de-coupling the `expireAfterUse` behaviour from the persist behaviour. 
**Solution**
- Remove `persist` check in `dlm.expireCompletedDrops`
- Updated the default values in `dlg.drop` so that if we only use the lifespan if we don't specify `expireAfterUse` in the Drop arguments. Otherwise, we would set `expireAfterUse` to `False` and then the lifespan would be set, which is the opposite of what …
> LIU-368: Enable Drop persistence

- .readthedocs.yaml
My previous commit missed the install requirements.txt from the new RTD config: https://blog.readthedocs.com/defaulting-latest-build-tools/. 
This is (still) leading to build failures for our documentation (albeit different build failures). 
https://readthedocs.org/projects/daliuge/builds/24361205/
> Fix missing rtd_sphinx_them install directive

- .readthedocs.yaml
The previous PR had the indentation off.
> Fix indentation error

- daliuge-translator/dlg/dropmake/web/translator_rest.py
This PR addresses https://github.com/ICRAR/daliuge/issues/255, in which I was not able to generate and deploy physical graphs because only a single node was being returned to the translator when the ManagerClient was queried for current nodes. 
This is only an issue with the Server deploy method; the Browser Direct method is working fine. 
The server and the Browser Direct method use different REST calls: 
- Server: \gen_pg
- Browser Direct: \gen_pg_spec
This is likely due to their requiring different pieces of information at runtime. 
They do get the same list of nodes, albeit in different through different methods. What they do with this list, however, is the difference.
**`\gen_pg`, Server**
https://github.com/ICRAR/daliuge/blob/bf3a8fcda936ed13d8dd41b893ccce560c529275/daliuge-translato …
> Add manager host to list of nodes when deploy method is Server

- daliuge-engine/dlg/apps/pyfunc.py
- daliuge-engine/dlg/named_port_utils.py
Previously, we addressed the issue that the positional parameter option currently does not work for Docker and Bash applications; a temporary fix was introduced in #248. 
Unfortunately, that solution did not allow for the potential Keyword-and-Positional argument combination, which is used in the `PyFunc` DROP classes. By commenting out the addition to `portargs` to fix positional arguments for Docker and Bash apps, I inadvertently broke the PyFunc apps. 
I have added a flag to the `identify_named_ports` methods that allows for the addition of positional arguments to the keyword argument dictionary, which required for the PyFunc drops to work. 
I have also added some support functions to reduce the incidence of duplicated coded in `replace_named_ports`, to improve readability and make a …
> Improve support for keyword-positional arguments

- daliuge-translator/dlg/dropmake/lg.graph.schema
Deleted old branch (eagle-1231), reproduced this work in new branch (eagle-1231-2).
Adds the 'encoding' attribute to fields in the JSON schema for logical graphs. Possible values of the attribute are:
- "binary"
- "pickle"
- "dill" (default)
- "npy"
- "base64"
- "utf-8"
> Added 'encoding' attribute to fields in LG schema
